spring:
  application:
    name: running-info-analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/running-info-analysis-service
    username: root
    password: "password"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
