server:
  port: 8081
spring:
  application:
    name: order # name will be used in eureka
  cloud:
    stream:
      bindings:
        output: order
#com:
#  qz:
#    payment: http://localhost:8082
#    order:
#      receiver: http://localhost:8083
#    restaurant: http://localhost:8080